version: "3.7"
services:
  squid:
    build: docker/squid
    working_dir: /app
    command: -NYCd 1
    ports:
      - 3128:3128
    volumes:
      - .:/app
      - ./docker/openssl/secure/proxy.crt:/etc/squid/proxy.crt
      - ./docker/openssl/secure/proxy.key:/etc/squid/proxy.key
      - ./docker/squid/squid.conf:/etc/squid/squid.conf

  openssl:
    build: docker/openssl
    command: -v
    working_dir: /app
    volumes:
      - .:/app

